### ISSUE TITLE
Navigating on afterCancel

### ISSUE THREAD

**Issue by wasong** [ZacharyRSmith/react-router-navigation-prompt#1]
Attempting to programmatically navigate on afterCancel using `history.push(...)` does result in expected action.

Expected:
I expect it to close my modal and navigate to my specified page.

Actual:
Closes modal but does not navigate away, no error is given.

I've tried creating a wrapper function for the onCancel, doing something like
```
() => {
    history.push('/')
    onCancel()
}
```

or other way around:
```
() => {
    onCancel()
    history.push('/')
}
```
console logs will run in there, but the history.push doesn't run.

----
Snippets of my code:
```
<NavigationPrompt
    renderIfNotActive
    when={loading}
    afterCancel={() => history.push('/route')}
    afterConfirm={() => history.push('/otherRoute')}
>
    ...
</NavigationPrompt>
```

(naive representation of my modal)
```
<Modal
    isOpen={isActive}
    onClose={onCancel} // handles closing modal clicking outside of modal area
>...</Modal>
```

**Comment by ZacharyRSmith** [comment]
Hi @wasong, [in the constructor for `<NavigationPrompt/>`, history is blocked](https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/master/src/index.js#L53).

This block is still in place [when `onCancel()` is run](https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/master/src/index.js#L94), but removed [when `onConfirm()` is run](https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/master/src/index.js#L102).

I am unsure that `<NavigationPrompt/>` is the correct solution for your use case, as its `onCancel()` is meant to keep the current route the same.  But if you wish to continue using it, I see two possible ways forward:

1. Update `when` to be false, then `history.push()`, or

2. Manually unblock history ( `<NavigationPrompt/>` will then not work until it is reconstructed):

```
const unblock = history.block();
unblock();
history.push('/route');
```

**Comment by wasong** [comment]
Thanks for the reply!
I'd just like to clarify something; where would solution 2 take place? In the `afterCancel` function? In some lifecycle method?

**Comment by ZacharyRSmith** [comment]
Solution 2 would take place anytime you'd like to forcefully unblock history.  In your case, you could put it in the `afterCancel` function.  Just don't forget to reconstruct `<NavigationPrompt/>` if you want to use it again.
