### ISSUE TITLE
Improve documentation,

### ISSUE THREAD

**Issue by Kapiroska** [ZacharyRSmith/react-router-navigation-prompt#14]
From what location should I import NavigationPrompt and ConfirmNavigationModal ?
I tried this way, but it doesn't work
`import { NavigationPrompt, ConfirmNavigationModal } from 'react-router-navigation-prompt';`
If I try to import this way:
`import NavigationPrompt from 'react-router-navigation-prompt';`
Where I should get ConfirmNavigationModal  component?

**Comment by ZacharyRSmith** [comment]
Thanks for opening an issue, @Kapiroska !  I've updated the README to indicate:

```javascript
import NavigationPrompt from 'react-router-navigation-prompt';

import ConfirmNavigationModal from './your-own-code';

<NavigationPrompt when={this.state.shouldConfirmNavigation}>
  {({onConfirm, onCancel}) => (
    <ConfirmNavigationModal when={true} onCancel={onCancel} onConfirm={onConfirm}/>
  )}
</NavigationPrompt>
```
