### ISSUE TITLE
search string is ignore on confirmation

### ISSUE THREAD

**Issue by doomsower** [ZacharyRSmith/react-router-navigation-prompt#20]
Hi there! Thanks for this useful module!

**Do you want to request a *feature* or report a *bug*?**

Bug, I believe [here](https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/799450945c2f3524172767fed007b59d31f21f72/src/index.js#L108)

**What is the current behavior?**

I have a form where user is able to change input language. This is done via search part of location. I.e. `https://domain/regions/:regionId/settings#main` is English version, navigating to `https://domain/regions/:regionId/settings#main?lang=es` should fill form with Spanish data, but if English data is unsaved, dialog should pop up. And also hash part of the location is used to switch between tabs, so this should not trigger dialog. My `when` condition looks like: 
```js
  shouldBlockNavigation = (cur: Location, nxt: Location) => {
    const { anyTouched } = this.props; // redux-form props
    return anyTouched && (nxt.pathname !== cur.pathname || nxt.search !== cur.search);
  };
```

When I try to navigate to a location that differs from current in search part only, my confirmation dialogs pops up, but on confirmation the search part remains the same. For changes in location that involve changing pathname everything works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use `when` function provided above and navigate to a location that has different search but same pathname.

**What is the expected behavior?**

After confirmation, should navigate to exactly intended location, pathname, hash, search should not be modified.

**Please post the output of `npm list react react-router react-router-dom react-router-navigation-prompt` (with redactions if needed).**

```
├── react@16.2.0 
├── react-router@4.2.0 
├─┬ react-router-dom@4.2.2 
│ └── react-router@4.2.0  deduped
└── react-router-navigation-prompt@1.5.5 
```

**Comment by ZacharyRSmith** [comment]
#21 fixes this, and i just published to npm.  thank you for opening this issue and doing such a thorough issue!
