### ISSUE TITLE
Children does not show

### ISSUE THREAD

**Issue by SergeyShablenko** [ZacharyRSmith/react-router-navigation-prompt#27]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

fires native popup

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

should show children, but it does not even call children function

**Please post the output of `npm list react react-router react-router-dom react-router-navigation-prompt` (with redactions if needed).**

├── react@16.3.1 
├── react-router@4.2.0 
├── react-router-dom@4.2.2 
└── react-router-navigation-prompt@1.6.0 

```javascript
<NavigationPrompt when={(from, to) => !to && this.props.cart.orders.length}>
        {
          ({ onConfirm, onCancel }) => {
            return <ConfirmModal show={true}
                                 title="Confirm Leaving"
                                 question="You have goods in the shopping cart. <br /> Do you want to continue shopping?"
                                 onSubmit={onConfirm}
                                 onHide={onCancel} />;
          }
        }
      </NavigationPrompt>
```

**Comment by ZacharyRSmith** [comment]
Thanks for the issue, @SergeyShablenko .

Navigation away from your site, reload, or closing tab/window fires the native popup in most browsers.  Is this the case for you, or is the navigation to another one of your routes?

**Comment by SergeyShablenko** [comment]
> Navigation away from your site, reload, or closing tab/window fires the native popup in most browsers

Yep, this is my case

**Comment by ZacharyRSmith** [comment]
I think I remember seeing a hack to do that, but unfortunately I cannot remember.

I am closing this issue because I know of no non-hack way to support the desired behavior.

Gook luck!
