### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by gpbl** [ZacharyRSmith/react-router-navigation-prompt#33]
I love this project, thanks a lot for your work, it has been very useful ❤️

I wonder if you could [add a changelog](https://keepachangelog.com/) or at least tag the releases on github to know what's changing when upgrading the component. Thanks 🙏!

**Comment by ZacharyRSmith** [comment]
Thanks for your kind words, @gpbl !

Great idea, thanks!  I hope nothing broke for you recently?  I will try to add a changelog within the new few days.  Cheers!

**Comment by gpbl** [comment]
you are welcome! No breaks here, thanks, just before upgrading we need to know why we should upgrade :)

**Comment by ZacharyRSmith** [comment]
@gpbl , i added this https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/master/CHANGELOG.md

please let me know if there are _change_s you'd like to see in the _change_log ; )

**Comment by gpbl** [comment]
That's great, thanks a lot @ZacharyRSmith !
