### ISSUE TITLE
Modal not Showing up

### ISSUE THREAD

**Issue by dumblole** [ZacharyRSmith/react-router-navigation-prompt#34]
**Do you want to request a *feature* or report a *bug*?**
Help
**What is the current behavior?**
Modal not showing up when form is dirty

**If the current behavior is a bug, please provide the steps to reproduce.**

Install https://github.com/djorg83/react-bootstrap-sweetalert
import `import SweetAlert from "react-bootstrap-sweetalert";`
```
<NavigationPrompt when={this.state.formDirty}>
          {({ onConfirm, onCancel }) => (
            <SweetAlert
              warning
              showCancel
              confirmBtnText="Yes, delete it!"
              confirmBtnBsStyle="danger"
              cancelBtnBsStyle="default"
              title="Are you sure?"
              onConfirm={this.deleteFile}
              onCancel={this.onCancelDelete}
            >
              You will not be able to recover this imaginary file!
            </SweetAlert>
          )}
        </NavigationPrompt>
```
On input box change, set `formDirty to true`

**What is the expected behavior?**
When I click on a link to a different part of the website, show the modal when `formDirty` is `true`

**Comment by dumblole** [comment]
Turns out I just needed to import react-router.

**Comment by dumblole** [comment]
@ZacharyRSmith Sorry, my bad, I thought it had to do with react-router. I was still trying to get my application to work. Now I'm sure you do not need to import react-router, although I'm pretty sure you need react-router to work. 
Also, I'm not sure if this is intended, but changing state right before form navigation will not have an effect on whether the modal will show up or not. But it does have on an effect on the modal contents. I think this is because the moment that (I used `formDirty`) `formDirty` was true, the package already sets a course in making `isActive` true. I have not tried using a promise to see if the state will set first even though I think nothing in the package is asynchronous. Please correct me if I'm wrong.

**Comment by dumblole** [comment]
Also, to anyone that plans on using SweetAlert, this is what I eventually did.
```
<NavigationPrompt when={this.state.onFormDirty}>
          {({ isActive, onConfirm, onCancel }) => {
            if (isActive) {
              swal({
                title: this.state.modalTitle,
                text: this.state.modalText,
                icon: this.state.modalIcon,
                buttons: this.state.modalButtons,
                dangerMode: true,
                closeOnEsc: false,
                closeOnClickOutside: false
              }).then(willDelete => {
                if (willDelete) {
                  onConfirm();
                } else {
                  onCancel();
                  this.hideModal(); //swal.close()
                }
              });
            }
          }}
        </NavigationPrompt>
```

**Comment by ZacharyRSmith** [comment]
i haven't seen this pattern before with NavigationPrompt.  thanks for sharing!
