### ISSUE TITLE
Navigate user to the desired location afterConfirm or afterCancel.

### ISSUE THREAD

**Issue by nageshkatna** [ZacharyRSmith/react-router-navigation-prompt#43]
Hi, I want the user to navigate to the location where the user was navigation afterConfirming or canceling. But I couldn't find any access to the location on it. Is there anyway I could achieve it?

**Comment by ZacharyRSmith** [comment]
Hi @nageshkatna , when the user confirms, they should navigate to where they were trying to go.  If this is not the case, maybe you're not using BrowserHistory?

**Comment by nageshkatna** [comment]
Hi, Thanks a lot for the reply. I am new to react, It would be great if you can explain more where should I use BrowserHistory code.

**Comment by nageshkatna** [comment]
I have used the prompt like this
I rendered this code
```
<NavigationPrompt
                beforeConfirm={this.cleanup}
                when={isBlocking}
                afterConfirm={this.props.history.push('/production')}
                afterCancel={<Redirect to={'/production'} />}
            >
                
                {({ isActive }) => {
                    
                    if (isActive && counter===0) {
                        // var that=this;
                        
                        counter++;
                        console.log("counter")
                        console.log(counter)
                        isActive=false;
                    return (
                        this.showPrompt()
                    );
                    }
                    
                }}
            </NavigationPrompt>
```
Then in return i call my prompt by calling a function called showprompt

```
showPrompt(){
        
        var that=this;
        confirm({
            title: 'Do you want to Save your changes',
            content: 'You are moving to another page without saving your editing. Do you want to Save or Discard your changes?',
            okText: 'Save',
            cancelText: 'Discard',
            onOk() {
                that.updateClick();
            },
            onCancel() {
            },
          });
    }
```
okOk() i Called my update function which upates the data. I want to send the user to the page on which they wanted to navigate. So according to it where can i use the Browser history and how? 
I have imported the Navigation prompt like this
`import NavigationPrompt from "react-router-navigation-prompt";`

**Comment by ZacharyRSmith** [comment]
react-router shows how to use its BrowserHistory: https://reacttraining.com/react-router/web/api/BrowserRouter

As seen in this repo's README, you need to pass onConfirm() and onCancel(), and call them when the user confirms/cancels navigation
```js
<NavigationPrompt when={this.state.shouldConfirmNavigation}>
  {({ onConfirm, onCancel }) => (
    <ConfirmNavigationModal
      when={true}
      onCancel={onCancel}
      onConfirm={onConfirm}
    />
  )}
</NavigationPrompt>;
```

Good luck!
