### ISSUE TITLE
react-router-dom is included in bundle

### ISSUE THREAD

**Issue by tu4mo** [ZacharyRSmith/react-router-navigation-prompt#5]
Seems that your es bundle is including react-router-dom, making it weigh over 200 KB.

**Comment by ZacharyRSmith** [comment]
Thank you for pointing that out!  Please PR if you have a fix.

**Comment by RikuVan** [comment]
Isn't it just a matter of moving react and react-dom them to the devDependencies? Having them as dependencies might also cause an app two load to incompatible versions.

**Comment by RikuVan** [comment]
Yeah, thanks @tu4mo. I think as it is this lib could result in two different versions of react-dom and react being loaded, leading to weird errors.

**Comment by RikuVan** [comment]
Wouldn't it also be better to move react and react-dom to devDependencies in your package.json? This seems to be the practice, for example: https://github.com/reactabular/reactabular/blob/master/package.json

**Comment by tu4mo** [comment]
@RikuVan I think that's the dev environment setup for reactabular. The actual components have React as peerDependencies: https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/package.json. 

Anyhow, I didn't look like React is in the es bundle, it's required outside: https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/master/es/index.js#L139

**Comment by ZacharyRSmith** [comment]
published as v1.5.3.  Thanks @tu4mo !
