### ISSUE TITLE
Update peerDependency for react-router-dom to include v5

### ISSUE THREAD

**Issue by jeffvandyke** [ZacharyRSmith/react-router-navigation-prompt#50]
After upgrading to react-router-dom 5, running `npm install` gives this message:
```
npm WARN react-router-navigation-prompt@1.8.5 requires a peer of react-router-dom@^4.2.2 but none is installed. You must install peer dependencies yourself.
```
React router 5 is actually a backwards compatible release, only with build output reshuffling (see [react-router 5 release notes](https://reacttraining.com/blog/react-router-v5/)). I performed some testing, and both the native and the in-browser navigation prompt behavior work fine after the upgrade - the prompt is able to prevent or advance a route change when using the hash router.

I think all that needs to be done is updating the peer dependency to allow v4 or v5, but I'm not certain on the best way to do that.

Output of `npm list react react-router react-router-dom react-router-navigation-prompt`:
```
npm list react react-router react-router-dom react-router-navigation-prompt
my-app-client@1.0.0 /home/my-user/repos/my-app-client
├── react@16.8.6
├─┬ UNMET PEER DEPENDENCY react-router-dom@5.0.0
│ └── react-router@5.0.0
└── react-router-navigation-prompt@1.8.5

npm ERR! peer dep missing: react-router-dom@^4.2.2, required by react-router-navigation-prompt@1.8.5
```

**Comment by ZacharyRSmith** [comment]
that makes 2 of us, but i went with: https://github.com/ZacharyRSmith/react-router-navigation-prompt/commit/3426514e101a1cf7d0ce669b5071d0609f5fbbca

updated on npm
