### ISSUE TITLE
Can't customize Prompt UI with own component

### ISSUE THREAD

**Issue by ningo-agilityio** [ZacharyRSmith/react-router-navigation-prompt#53]
Hi team,
I am using `react-router: 4.3.1` and `react-router-dom: 4.3.1`, whatever I tried to follow your sample on README. I can't see my own modal instead default prompt on Chrome.
My environment and dependencies are:
- Default Chrome is `Version 75.0.3770.100 (Official Build) (64-bit)`
- "react-dom": "^16.8.3"
- "react-router": "^4.3.1"
- "react-router-dom": "^4.3.1"
- "react-router-navigation-prompt": "^1.8.7",
- "react-scripts": `"2.0.4"`

Could you tell me did I missed any configuration?
This is my default popup.
![Screen Shot 2019-06-24 at 6 06 05 PM](https://user-images.githubusercontent.com/9548275/60014344-fc1ee280-96aa-11e9-9212-2e1e5f5b8741.png)

**Comment by ZacharyRSmith** [comment]
Hi @ningo-agilityio , it does look like you missed some configuration.  Would you please provide all the code that you can?  Thanks!

**Comment by ningo-agilityio** [comment]
Yes. Below is all my code:

1. The same as `PreventTransitionPrompt.js`, but I changed my own modal here
```
return (
      <>
        {/* React Router prompt, callback will return true to allow transition or dialog key to prevent */}
        <Prompt when={when} message={this.handleTransition} />

        {/* Example MUI dialog to show when open. You could make this
            totally customizable or a complete one-off. */}
        { open &&
          <ConfirmDelete
            description={message}
            buttonNoText='Stay on this page'
            buttonYesText={'Continue & don\'t save'}
            onSubmit={this.handleClose}
            handleClosePopup={this.handleClose}
            buttonPosition='center'
          />
        }
      </>
)

2. This is my component where called `PreventTransitionPrompt`. I'm writing a functional component HOC. And `Home.js` call this HOC.
```
const withForm = (Component, internalHook) => {
  return memo(props => {
    const [shouldBlockNavigation, toggleBlockNavigation] = useState(false)

    const hookData = internalHook({
      ...props,
      toggleBlockNavigation
    })

    // Watch to show confirmation before leaving changes
    useEffect(
      () => {
        if (!_.isEmpty(hookData.changes)) {
          toggleBlockNavigation(true)
        }
      },
      [hookData.changes]
    )

    return (
      <>
        <PreventTransitionPrompt
            when={shouldBlockNavigation}
            message='Please save your changes.'
        />

        <Component
          {...props}
          {...hookData}
        />
      </>
    )
  })
}

```

3. My configuration in main route:
```
import React, { Component } from 'react'
import {
  BrowserRouter as Router,
  Route,
  Switch,
  Redirect,
} from 'react-router-dom'
import { ApolloProvider } from 'react-apollo'

// Page
import Home from 'pages/Home'

// Constants and helpers
import ROUTER from 'constants/Router'
import client from 'config/Apollo'

const getUserConfirmation = (dialogKey, callback) => {
  // use "message" as Symbol-based key
  const dialogTrigger = window[Symbol.for(dialogKey)];
  if (dialogTrigger) {
    // pass the callback to delegate
    // to the invoked dialog
    return dialogTrigger(callback);
  }

  // Fallback to allowing navigation
  callback(true);
}

class MainRouter extends Component<Props> {
  render() {
    return (
      <ApolloProvider client={client}>
        <Router getUserConfirmation={getUserConfirmation}>
            <Switch>
              <Route exact path={ROUTER.HOME} component={Home} />
            </Switch>
        </Router>
      </ApolloProvider>
    )
  }
}

export default MainRouter
```

**Comment by ningo-agilityio** [comment]
Yes. Below is all my code:

1. The same as `PreventTransitionPrompt.js`, but I changed my own modal here
```
return (
      <>
        {/* React Router prompt, callback will return true to allow transition or dialog key to prevent */}
        <Prompt when={when} message={this.handleTransition} />

        {/* Example MUI dialog to show when open. You could make this
            totally customizable or a complete one-off. */}
        { open &&
          <ConfirmDelete
            description={message}
            buttonNoText='Stay on this page'
            buttonYesText={'Continue & don\'t save'}
            onSubmit={this.handleClose}
            handleClosePopup={this.handleClose}
            buttonPosition='center'
          />
        }
      </>
)

2. This is my component where called `PreventTransitionPrompt`. I'm writing a functional component HOC. And `Home.js` call this HOC.
```
const withForm = (Component, internalHook) => {
  return memo(props => {
    const [shouldBlockNavigation, toggleBlockNavigation] = useState(false)

    const hookData = internalHook({
      ...props,
      toggleBlockNavigation
    })

    // Watch to show confirmation before leaving changes
    useEffect(
      () => {
        if (!_.isEmpty(hookData.changes)) {
          toggleBlockNavigation(true)
        }
      },
      [hookData.changes]
    )

    return (
      <>
        <PreventTransitionPrompt
            when={shouldBlockNavigation}
            message='Please save your changes.'
        />

        <Component
          {...props}
          {...hookData}
        />
      </>
    )
  })
}

```

3. My configuration in main route:
```
import React, { Component } from 'react'
import {
  BrowserRouter as Router,
  Route,
  Switch,
  Redirect,
} from 'react-router-dom'
import { ApolloProvider } from 'react-apollo'

// Page
import Home from 'pages/Home'

// Constants and helpers
import ROUTER from 'constants/Router'
import client from 'config/Apollo'

const getUserConfirmation = (dialogKey, callback) => {
  // use "message" as Symbol-based key
  const dialogTrigger = window[Symbol.for(dialogKey)];
  if (dialogTrigger) {
    // pass the callback to delegate
    // to the invoked dialog
    return dialogTrigger(callback);
  }

  // Fallback to allowing navigation
  callback(true);
}

class MainRouter extends Component<Props> {
  render() {
    return (
      <ApolloProvider client={client}>
        <Router getUserConfirmation={getUserConfirmation}>
            <Switch>
              <Route exact path={ROUTER.HOME} component={Home} />
            </Switch>
        </Router>
      </ApolloProvider>
    )
  }
}

export default MainRouter
```

**Comment by ningo-agilityio** [comment]
I tried to remove ApolloProvider and Switch as well, but it still doesn't work. Could you help to check if you figure out the issue?

**Comment by ZacharyRSmith** [comment]
Hi @ningo-agilityio , first off I'm not sure if ApolloProvider is messing with anything so I agree removing that while debugging is a good idea.

Have you tried removing getUserConfirmation from <Router />?

Are you naming react-router-navigation-prompt as Prompt?  Ie, `import Prompt from 'react-router-navigation-prompt'?  I see the name Prompt is your code, I want to make sure you do not think installing react-router-navigation-prompt changes react-router's Prompt and are using it.

**Comment by ningo-agilityio** [comment]
A little bit confused about what you are mentioning.
I did remove:
- ApolloProvider
- getUserConfirmation from Router
- And I am using `import NavigationPrompt from 'react-router-navigation-prompt'`

**Comment by ZacharyRSmith** [comment]
Ohhh sorry I missed in your pic that you are navigating away from the page.

As noted in the README:

Note: Navigation away from your site, reload, or closing tab/window will also prompt navigation confirmation when <NavigationPrompt/>'s props.when is truthy. `Usually, browsers handle this navigation UX themselves, leading to vanilla alert boxes`. Also, many browsers require users to interact with your site before confirming navigation away.

Is the alert box still "vanilla" when navigating within your site?

I remember reading that it may be possible to display non-vanilla alerts in the exceptional cases listed in the README, but it seemed to be an anti-pattern.

**Comment by ningo-agilityio** [comment]
Yes, the alert box is still "vanilla" when navigating within your site.
It still didn't work even I navigated inside site e.g from `/home` to `/about-us`.
So does your lib support this? As I checked, in your sample, it still works when navigating from `/` to `/test`, right?

**Comment by ningo-agilityio** [comment]
Hey, it worked for me. I used `<a>` in incorrect way. It should be `Link` of react-router-dom.
But still so hard to control it. Thanks for your support.
Let close this issue.

**Comment by ZacharyRSmith** [comment]
I'm glad to hear it worked.  Cheers!
