### ISSUE TITLE
Reload shows vanilla alert

### ISSUE THREAD

**Issue by reintroducing** [ZacharyRSmith/react-router-navigation-prompt#54]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I've got code with this component working great when I'm navigating on my site. However, simply reloading the page shows the vanilla JS alert box. From reading the docs, it sounds like this should still trigger my custom rendered component. Am I misunderstanding?

**If the current behavior is a bug, please provide the steps to reproduce.**

My code is pretty simple, right at the top of my component:
```js
<NavigationPrompt when={isFormDirty}>
    {({onConfirm, onCancel}) => (
        <>
            <Button color="secondary" onClick={onCancel}>
                Cancel
            </Button>
            <Button color="primary" onClick={onConfirm}>
                Confirm
            </Button>
        </>
    )}
</NavigationPrompt>
```

**What is the expected behavior?**
Just landing on the page with this component and `isFormDirty = true`, a reload should also show the two buttons not the vanilla alert dialog.

**Please post the output of `npm list react react-router react-router-dom react-router-navigation-prompt` (with redactions if needed).**
```bash
├── react@16.9.0
├─┬ react-router-dom@5.0.1
│ └── react-router@5.0.1
└── react-router-navigation-prompt@1.8.7
```

**Comment by ZacharyRSmith** [comment]
@reintroducing , thanks for your thorough issue.  Unfortunately, this is expected behavior.  I clarified the README:

```
Note: Navigation away from your site, reload, or closing tab/window will also prompt navigation confirmation when <NavigationPrompt/>'s props.when is truthy. However, for security concerns browsers usually handle this navigation UX themselves, leading to vanilla alert boxes. Also, many browsers require users to interact with your site before confirming navigation away.
```

**Comment by reintroducing** [comment]
Makes perfect sense, appreciate the clarification. Great bit of code by the way, saved me a lot of time in writing my own implementation and works flawlessly for my purposes, appreciate it.

**Comment by ZacharyRSmith** [comment]
Thanks!  Much of the credit goes to others who've contributed.
