### ISSUE TITLE
There is no easy way to consume flow typings

### ISSUE THREAD

**Issue by 102** [ZacharyRSmith/react-router-navigation-prompt#55]
**Do you want to request a *feature* or report a *bug*?**

This is likely a bug

**What is the current behavior?**

Using `import NavigationPrompt from 'react-router-navigation-prompt';` within flow codebase results in `NavigationPrompt` being typed as `any`

**If the current behavior is a bug, please provide the steps to reproduce.**

See current behavior

**What is the expected behavior?**

It can have already defined typings from `src/index.js`.

For the moment, this can be achieved by using

- `import NavigationPrompt from 'react-router-navigation-prompt/src';`
- copy-pasting content of the `src/index.js` into `es/index.js.flow` with the help of something like `patch-package`
- users can add following line to the `options` in `.flowconfig`: 
    `module.name_mapper='^react-router-navigation-prompt$' -> '<PROJECT_ROOT>/node_modules/react-router-navigation-prompt/src/index.js'`

neither of these looks anyhow good from lib user experience

**Please post the output of `npm list react react-router react-router-dom react-router-navigation-prompt` (with redactions if needed).**

```
├── flow-bin@0.84.0 
├── react@16.8.6 
├─┬ react-router-dom@4.3.1 
│ └── react-router@4.3.1 
└── react-router-navigation-prompt@1.8.8 
```

**Comment by ZacharyRSmith** [comment]
Thanks @102 for this thorough issue!  Would you please open a PR to fix this?  Thanks!

**Comment by 102** [comment]
Yes, I will take a look at it
