### ISSUE TITLE
Default prompt shows when nextLocation is undefined

### ISSUE THREAD

**Issue by PetrivskyiTaras** [ZacharyRSmith/react-router-navigation-prompt#58]
It cannot show a custom prompt when "nextLocation" is undefined. The case when you open application directly by link and when back button is pressed you'll see default prompt instead of your custom.

**Comment by ZacharyRSmith** [comment]
Thanks for the issue, @PetrivskyiTaras !  However, I think this behavior is expected because you are navigating away from your site, which as noted in the README is usually handled by browsers with default prompt for security concerns.  Please reopen this issue if you disagree

```
Note: Navigation away from your site, reload, or closing tab/window will also prompt navigation confirmation when <NavigationPrompt/>'s props.when is truthy. However, for security concerns browsers usually handle this navigation UX themselves, leading to vanilla alert boxes. Also, many browsers require users to interact with your site before confirming navigation away.
```

**Comment by PetrivskyiTaras** [comment]
My problem is I want to show my popup with my message in this case, is it possible?

**Comment by ZacharyRSmith** [comment]
@PetrivskyiTaras I don't think so.  Please let me know if you find a way!

**Comment by PetrivskyiTaras** [comment]
@ZacharyRSmith thanks for the answer!
