### ISSUE TITLE
Can we get next or previous location in afterConfirm/afterCancel callback

### ISSUE THREAD

**Issue by sibinx7** [ZacharyRSmith/react-router-navigation-prompt#59]
Do we get previous and next location in afterConfirm/afterCancel callback.  It will be a nice addition so user can navigate to the original next location.

**Comment by ZacharyRSmith** [comment]
Thanks for the issue, @sibinx7 !

When the user cancels navigation, they are not navigated anywhere.  So, I don't think it makes sense to pass a location to afterCancel.

When the user confirms navigation, they are already navigated to what triggered <NavigationPrompt />.  So, I don't think it makes sense to pass a location to afterConfirm.

Please reopen this issue if this does not make sense.

**Comment by sibinx7** [comment]
@ZacharyRSmith I have one feature,  afterConfirm , form need to save with submitted flag true, and afterCancel, form need to save with submitted flag false, then both redirect to `next` location.

Thanks for your support.

**Comment by ZacharyRSmith** [comment]
Unfortunately that feature would break this component's logic, which is: cancel cancels redirection and confirm continues redirection.  You could change how you're using this component or create your own fork to enable this feature.

Cheers!
