### ISSUE TITLE
Reusing the prompt issue

### ISSUE THREAD

**Issue by muscaiu** [ZacharyRSmith/react-router-navigation-prompt#61]
I'm using this library in an electron/react app to prevent the user from navigating to another route but only when the user is on the `Play Page`.

I'm reusing the WarningModal to show `Are you sure you want to Quit?` modal when the user is clicking on the X button trying to close the app.

**Both modals work fine except for 1 case.** 
When the user is on the Play Page and clicks X, 
- the modal shows up correctly, 
- the user confirms he wants to quit,
- the `{ type: SET_DIALOG_TOGGLE, payload: 'close' }` action fires and `console.log says close the app`
- for some reason `remote.getCurrentWindow().close();` is not being executed, the app is not closed and also the hot-reloader stops working at that point.

I also tried creating completely separated modals and same thing happens.

Any idea what could be the issue or what else should i try?

I'm using this code in the NavBar:
```
      {dialogOpen ? (
        <WarningDialog
          quit
          open={dialogOpen}
          title="Quit?"
          content="Are you sure you want to quit?"
          cancelButtonText="Return"
          confirmButtonText="Quit"
          onCancel={() => dispatch({ type: SET_DIALOG_TOGGLE })}
          onConfirm={() => dispatch({ type: SET_DIALOG_TOGGLE, payload: 'close' })}
        />
      ) : (
        isPlayPage && (
          <NavigationPrompt when>
            {({ onConfirm, onCancel }) => (
              <WarningDialog
                title="Warning!"
                content="You will lose the unsaved progress"
                cancelButtonText="Return to Game"
                confirmButtonText="Quit Game"
                open
                onCancel={onCancel}
                onConfirm={onConfirm}
              />
            )}
          </NavigationPrompt>
        )
      )}
....
reducer 
import { remote } from 'electron';

const initialState = {
  dialogOpen: false,
};

export default (state = initialState, action) => {
  switch (action.type) {
    case SET_DIALOG_TOGGLE:
      if (action.payload === 'close') {
        console.log('close the app')
        remote.getCurrentWindow().close();
      }
      return { ...state, dialogOpen: !state.dialogOpen };
    default:
      return state;
  }
};


```

**Comment by ZacharyRSmith** [comment]
@muscaiu thanks for the issue! Unfortunately I do not know what is happening, and do not have the time to look into it.

If I understand you correctly, then the 1st line of the below is running but not the 2nd, correct?

        console.log('close the app')
        remote.getCurrentWindow().close();

If so, how do you know         remote.getCurrentWindow().close() is not executed?  Is it possible that is is executed, but its results are not what you expect?

**Comment by muscaiu** [comment]
@ZacharyRSmith that's correct. 
Even though both lines seem to be executed, the app is not being closed. It's definitely related to the Prompt, but i don't understand why this is happening, because all the logic seems to be fine.

I was wondering maybe you would have a clue why it doesn't work in this particular case.

**Comment by muscaiu** [comment]
Omfg i just realized what's wrong and now it's working fine.
I wasn't returning (didn't even thought about doing it honestly)....
```
return remote.getCurrentWindow().close();
```

**Comment by ZacharyRSmith** [comment]
Haha I love/hate it when the fix is so simple!
