### ISSUE TITLE
feature: can you provide a downloadable zip for v1.8.10

### ISSUE THREAD

**Issue by ruidai3333** [ZacharyRSmith/react-router-navigation-prompt#64]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Releases after 1.7* are missing in `releases`. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Would you mind add v1.8.10 (I specifically need this version but it would nice to have the latest as well) and provide a downloadable package? Thank you!

**Please post the output of `npm list react react-router react-router-dom react-router-navigation-prompt` (with redactions if needed).**

**Comment by ZacharyRSmith** [comment]
@ruidai3333 , v1.8.11 is now available as a release
