### ISSUE TITLE
Disable browser prompt on reload if navigation prompt.when is truthy

### ISSUE THREAD

**Issue by shreyashah7** [ZacharyRSmith/react-router-navigation-prompt#65]
Is there any option of disabling the browser prompt on reload if my page is dirty?

<img width="423" alt="Screen Shot 2020-06-10 at 12 38 53 PM" src="https://user-images.githubusercontent.com/6551265/84310985-62e51800-ab17-11ea-9748-d5be16376fe2.png">

**Comment by shreyashah7** [comment]
@ZacharyRSmith Is there a way i can disable those vanilla alert boxes?

**Comment by ZacharyRSmith** [comment]
@shreyashah7 not with this module. I think there might be a way to hack some browsers so you can provide a custom alert box in such situations, but it is a security anti-pattern.
