### ISSUE TITLE
Question about when and afterConfirm

### ISSUE THREAD

**Issue by RoosterH** [ZacharyRSmith/react-router-navigation-prompt#70]
In my usage scenario, I do not want to pop up the confirmation message but I do want to call some functions in afterConfirm().  I can't seem to find that combination.  

Here is how I define it:
```
	<NavigationPrompt
		afterConfirm={() => {
			formContext.setIsInsideForm(false);
			removeEventFormData();
		}}
		
		when={(crntLocation, nextLocation) => 
                         !OKLeavePage &&
			(!nextLocation ||
			          !nextLocation.pathname.startsWith(
					crntLocation.pathname
				))
	        }>
```
When OKLeavePage is true, confirmation message does not pop up but at the same time it skips afterConfirm. I cannot put those function calls in beforeConfirm because if confirmation does pop up and user hit CANCEL removeEventFormData wipes out all the data.

Is there anyway that I can work around it? 

Much appreciated!

**Comment by ZacharyRSmith** [comment]
please let me know if this scenario is correct:

given a user tries to navigate away
when OKLeavePage is true
then:
- the user should _not_ be prompted to confirm navigation, and
- these calls should be made: 1. formContext.setIsInsideForm(false); 2. removeEventFormData();

If this scenario is correct, then making those calls is not the responsibility of NavigationPrompt. I recommend making those calls elsewhere. However, i think this is a workaround:
```js
<NavigationPrompt
    afterConfirm={() => {
        formContext.setIsInsideForm(false);
        removeEventFormData();
    }}
    when={(crntLocation, nextLocation) => {
        if (OKLeavePage) {
            formContext.setIsInsideForm(false);
            removeEventFormData();
            return false;
        } else {
            return !nextLocation
                || !nextLocation.pathname.startsWith(crntLocation.pathname);
        }
    }}
>
```

Please re-open the issue if this does not answer your question.

**Comment by RoosterH** [comment]
Thanks it works!  I was focusing finding answers from using any of the param provided by the package and missed this simple solution.  Thanks again!
