### ISSUE TITLE
页面刷新浏览器的时候可以把弹窗关闭吗或者跟离开页面时自定义页面的逻辑样式保持一致 页面刷新浏览器的时候可以把弹窗关闭吗或者跟离开页面时自定义页面的逻辑样式保持一致 Can I close the pop-up window when I refresh the browser or keep it consistent with the logic style of the custom page when I leave the page

### ISSUE THREAD

**Issue by liuxiansheng2018** [ZacharyRSmith/react-router-navigation-prompt#71]
![image](https://user-images.githubusercontent.com/35281468/106419721-0498eb00-6494-11eb-8c78-cbf229c28850.png)
![image](https://user-images.githubusercontent.com/35281468/106419739-124e7080-6494-11eb-9dc9-e4310d19c22e.png)

**Comment by ZacharyRSmith** [comment]
> Can I close the pop-up window when I refresh the browser...

If you mean, "can my code not prompt the user when the user refreshes the browser", then yes with this code:

```js
        <NavigationPrompt when={(currLocation, nextLocation) => {
          if (nextLocation === undefined) {
            return false;
          }
          return true;
        }}>
```

but this would also not prompt when the user navigates to another site or closes the tab.

> ...or keep it consistent with the logic style of the custom page when I leave the page

No, as indicated in this note in the README:
```
Note: Navigation away from your site, reload, or closing tab/window will also prompt navigation confirmation when <NavigationPrompt/>'s props.when is truthy. However, for security concerns browsers usually handle this navigation UX themselves, leading to vanilla alert boxes. Also, many browsers require users to interact with your site before confirming navigation away.
```
