### ISSUE TITLE
when => boolean not working on browser reload

### ISSUE THREAD

**Issue by dyenereks** [ZacharyRSmith/react-router-navigation-prompt#76]
Below `when` props works when route is changed but not when I just reload the page. It seems that it's not called when page is being reloaded.
```
<NavigationPrompt
      when={(
          { pathname: currentPath },
          { pathname: nextPath }
      ) => {
          if (currentPath !== nextPath)
              return hasUnsavedChanges();
          return false;
      }}
  />
```

**Comment by ZacharyRSmith** [comment]
Hi @dyenereks , what makes you think it's not called?

Navigation away from your site, reload, or closing tab/window will also prompt navigation confirmation when <NavigationPrompt/>'s props.when is truthy. However, **for security concerns browsers usually handle this navigation UX themselves, leading to vanilla alert boxes. Also, many browsers require users to interact with your site before confirming navigation away.**

**Comment by dyenereks** [comment]
I tried the boolean prop and it works perfectly fine even when closing/reloading tab/window
```
<NavigationPrompt
      when={hasUnsavedChanges()}
  />
```

but when I tried to compare the location pathnames, it doesn't trigger when reloading/closing the tab. Navigation away from my site works with both sample.

```
<NavigationPrompt
      when={(
          { pathname: currentPath },
          { pathname: nextPath }
      ) => {
          if (currentPath !== nextPath)
              return hasUnsavedChanges();
          return false;
      }}
  />
```

**Comment by ZacharyRSmith** [comment]
please try checking if nextLocation is defined before trying to destructure it

**Comment by ZacharyRSmith** [comment]
Please reopen if that does not work
