### ISSUE TITLE
Multiple BrowserRouter instances breaks NavigationPrompt

### ISSUE THREAD

**Issue by mellis481** [ZacharyRSmith/react-router-navigation-prompt#77]
If there are multiple `BrowserRouter` instances, `NavigationPrompt` doesn't work as expected.

https://oq16x.csb.app/sub/route1

1. Dirty form
2. Clicking the "Go to test" link works
3. Clicking the "Go to test (top-level)" link does not work

**Comment by ZacharyRSmith** [comment]
Thanks for the reproducing example!

I would not expect NavigationPrompt to work with multiple BrowserRouters. In your example, I change NavigationPrompt to react-router's Prompt, and it didn't work either. I just updated the README to call this out. Please reopen if it makes sense to.

**Comment by mellis481** [comment]
@ZacharyRSmith   Thanks for the quick response!

Considering that nested routes is something react router supports (https://reactrouter.com/web/example/nesting), I'm surprised and disappointed this library won't work with it.
