### ISSUE TITLE
Request: expose `action` to `when`

### ISSUE THREAD

**Issue by timhwang21** [ZacharyRSmith/react-router-navigation-prompt#78]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The `when` callback takes two arguments: previous location and next location. `block` from React Router also exposes `action`. It would be useful to expose this to `when` as a third argument. For example, one may want to not trigger the confirmation on `'REPLACE'` events.

In my case, we sometimes use 'REPLACE' to open subpages that still exist within the context of the "main" page, and we don't want the confirmation to pop up. This isn't a blocker for us as we can compare the two locations for root route or something, but using the action would be far easier.

If this is reasonable, I can file a PR!

**Comment by ZacharyRSmith** [comment]
@timhwang21 makes sense to me. Please PR. Thanks!

**Comment by ZacharyRSmith** [comment]
pub'd to npm: https://www.npmjs.com/package/react-router-navigation-prompt
